language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE andela_test;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD '1A2S3D';" -U postgres
env:
  - DB_URL="postgres://postgres:1A2S3D@localhost:5432/andela_test"
# command to run tests
script:
  - python -m pytest --cov=app app/tests/
after_success:
  - coveralls