language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

addons:
  postgresql: "10"
    apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
    global:
    - PGPORT=5432
    - SECRET_KEY="ABIGSECRET"
before_script:
  - psql -c 'CREATE DATABASE andela_test;' -U postgres
# command to run tests
script:
  - python -m pytest --cov=app app/tests/
after_success:
  - coveralls