language: python
sudo: false
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
before_script:
  - psql -c "CREATE DATABASE politico_test_db;" -U postgres
  - psql -c "CREATE USER politico WITH PASSWORD 'asd123';" -U postgres
env:
  - DB_URL="postgres://politico:asd123@localhost/politico_test_db"
# command to run tests
script:
  - python -m pytest --cov=app app/tests/
after_success:
  - coveralls